### ISSUE TITLE
Thanks So Much!

### ISSUE THREAD

**Issue by base698** [linktohack/evil-rsi#3]
I have been trying to get this functionality for months and finally found this.  Never got it working by setting the property.  

I can use emacs for irc, term and everything

**Comment by linktohack** [comment]
Thanks, @base698, did you try the snippets on the README? I think you can achieve a better result with either of the two, i.e. having raw string inserted in `ansi-term` etc...

**Comment by base698** [comment]
I tried the non-use-package example and it never worked.  I updated evil
mode to the 2016-01-30 version and tried it again and that didn't work
either.

Maybe using the use-package version?

**Comment by linktohack** [comment]
You can try either, the first version has bindings for only insert state, while the other works with motion state as well as for helm and mini buffer.

Just remember to run them before loading evil (via autoload, require or use-package), or it will too late.

Maybe I should integrate the package with the new facility, it's easier with one line configuration than ten...

**Comment by base698** [comment]
use-package version worked and ansi-term works better as you stated.
Thanks again!

**Comment by linktohack** [comment]
@base698, code updated if you prefer one-line-configuration...

**Comment by linktohack** [comment]
Cleaning up...
