### ISSUE TITLE
C-w in search state?

### ISSUE THREAD

**Issue by h35514n** [linktohack/evil-rsi#4]
Something I really miss from Vim is the ability to clear a backwards-kill a line or word when searching, i.e., after hitting `/` and entering some text, being able to clear the search term with `C-w`.

Do you know of any way to implement this? I've been searching fort the relevant state map command (i.e., evil-ex-state-map), but haven't had any luck so far.

Either way, thanks for this package! It's been a godsend.

**Comment by linktohack** [comment]
You can try this https://github.com/linktohack/evil-rsi/blob/master/evil-rsi.el#L68, I think it's enable by `evil-rsi` if you have `evil-want-C-w-delete` set to non-nil (you have to set the variable before load `evil`)

**Comment by h35514n** [comment]
Hmm...doesn't look like it. I've tried it with

``` lisp
(setq-default evil-want-C-w-delete t)
(require 'evil)
(evil-mode 1)
```

and with

``` lisp
(setq evil-want-C-w-delete t)
(require 'evil)
(evil-mode 1)
```

`C-w` just appends whatever's in the search bar with whatever word is currently under the point.

**Comment by linktohack** [comment]
Ah, in that case you must have `evil-search-module` search set to `isearch`. You can either set it to `evil-ex-search` or implement a command to somehow extract current search, delete last word and set it to `isearch-string`...

Something like this may help.

``` emacs-lisp
(setq isearch-string (with-temp-buffer
(insert isearch-string)
(backward-kill-word)
(bufer-string))
(isearch-search-and-update))
```

Haven't test myself but it should be like that

**Comment by h35514n** [comment]
> You can either set it to evil-ex-search or implement a command to somehow extract current search, delete last word and set it to isearch-string

That's great, thanks! I'll try that 😄
